### PR TITLE
Final Capstone Project

### PR DESCRIPTION
**Pull request by binyamolango**
# Hi Reviewer 👋

> Below are the implemented tasks while working on this project:

- Set up the project and installed necessary dependencies,
- Implemented login page.
- Added navigation.
- Added a footer to enhance the overall layout.
- Completed the UI for the main page, displaying a list of doctors.
- Finalized the UI for the doctor details page.
- Implemented the ability to add a doctor to the system.
- Added a new page for deleting doctors, complete with UI and functionality.
- Updated the doctor slice and created a component for deleting doctors.

_I am doing the project solo due to my coding partners leaving the group_
image

### CODE REVIEW

**Review by vichuge — COMMENTED** [review]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

mario_ladders


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

- It looks like I don't have an official way to add a new user, just login if I already have an account. Please consider add this functionality. This or add users on seeds and add instructions to know how to use it could works too. But I think to add a create user functionality is more according to the project.

image

- Please, consider to add tests in this part of the project. Nice work at this point. 

```
No tests found, exiting with code 0

Watch Usage: Press w to show more.
```
- This is an interesting way to do it. Where to find this links? Why don't try to save images inside the app and use the URL inside the app to use it?

image


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by binyamolango** [comment]
Hi @vichuge, Thank you so much for the valuable suggestions. I am about to apply the recommended changes but didn't fully understand the third suggestion on  the doctor picture link part. Can you explain to me more? Thanks

**Comment by binyamolango** [comment]
- Added tests for my components
- Added signup page
- Made sure that pictures are saved inside the app database

**Review by Meltrust — APPROVED** [review]
# **Wow, you did it 🎉**
Brilliant
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
applause

### To highlight


- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

**Pull request merged**
